main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
path('', views.home, name='home'),
path('about/', views.about, name='about'),
path('relationships/', views.relationships_index, name='index'),
path('relationships/<int:relationship_id>/', views.relationships_detail, name='detail'),
path('relationships/create/', views.RelationshipCreate.as_view(), name='relationship_create'),
path('relationships/<int:pk>/update/', views.RelationshipUpdate.as_view(), name='relationship_update'),
path('relationships/<int:pk>/delete/', views.RelationshipDelete.as_view(), name='relationship_delete'),
path('relationships/<int:relationship_id>/add_meeting/', views.add_meeting, name='add_meeting'),
path('traits/', views.TraitList.as_view(), name='traits_index'),
path('traits/<int:pk>/', views.TraitDetail.as_view(), name='traits_detail'),
path('traits/create/', views.TraitCreate.as_view(), name='traits_create'),
path('traits/<int:pk>/update/', views.TraitUpdate.as_view(), name='traits_update'),
path('traits/<int:pk>/delete/', views.TraitDelete.as_view(), name='traits_delete'),
path('relationships/<int:relationship_id>/assoc_trait/<int:trait_id>/', views.assoc_trait, name='assoc_trait'),
path('relationships/<int:relationship_id>/add_photo/', views.add_photo, name='add_photo'),
path('accounts/signup/', views.signup, name='signup'),
]

theaudacity/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Trait(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('traits_detail', kwargs={'pk': self.id})


class SigOther(models.Model):
    name = models.CharField(max_length=100)
    met = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    break_up = models.TextField(max_length=250)
    traits = models.ManyToManyField(Trait)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'sigother_id': self.id})
    

class Meetings(models.Model):
  date = models.DateField()
  location = models.CharField(max_length=100)
  rating = models.IntegerField("Rating out of 10")
  details = models.TextField(max_length=250)

  relationship = models.ForeignKey(SigOther, on_delete=models.CASCADE)

  class Meta:
    ordering = ['-date']

  def __str__(self):
    return f" We met on {self.date} at {self.location}"

class Photo(models.Model):
    url = models.CharField(max_length=200)
    relationship = models.ForeignKey(SigOther, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for relationship_id: {self.relationship_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Meetings

class MeetingsForm(ModelForm):
  class Meta:
    model = Meetings
    fields = ["date", "location", "rating", "details"]

main_app/views.py
from django.shortcuts import render,redirect
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic import ListView, DetailView
from .models import SigOther, Trait, Photo
from .forms import MeetingsForm
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

import uuid
import boto3


S3_BASE_URL = 'https://s3-us-west-1.amazonaws.com/'
BUCKET = 'catcollector-bg31'


def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

@login_required
def relationships_index(request):
    relationships = SigOther.objects.filter(user=request.user)
    return render(request, 'relationships/index.html', { 'relationships': relationships })

@login_required
def relationships_detail(request, relationship_id):
  relationship = SigOther.objects.get(id=relationship_id)
  traits_sigother_doesnt_have = Trait.objects.exclude(id__in = relationship.traits.all().values_list('id'))
  meetings_form = MeetingsForm()
  return render(request, 'relationships/detail.html', { 'relationship': relationship, "meetings_form": meetings_form, "traits": traits_sigother_doesnt_have })

class RelationshipCreate(LoginRequiredMixin, CreateView):
  model = SigOther
  fields = ['name', "met", "description", "break_up"]
  success_url = '/relationships/'
  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)

class RelationshipUpdate(LoginRequiredMixin, UpdateView):
  model = SigOther
  fields = '__all__'

class RelationshipDelete(LoginRequiredMixin, DeleteView):
  model = SigOther
  success_url = '/relationships/'

@login_required
def add_meeting(request, relationship_id ):
  form = MeetingsForm(request.POST)
  if form.is_valid():
    new_meeting = form.save(commit=False)
    new_meeting.relationship_id = relationship_id
    new_meeting.save()
  return redirect('detail', relationship_id=relationship_id)

@login_required
def assoc_trait(request, relationship_id, trait_id):
  SigOther.objects.get(id=relationship_id).traits.add(trait_id)
  return redirect('detail', relationship_id=relationship_id)

class TraitList(LoginRequiredMixin, ListView):
  model = Trait

class TraitDetail(LoginRequiredMixin, DetailView):
  model = Trait

class TraitCreate(LoginRequiredMixin, CreateView):
  model = Trait
  fields = ['name']

class TraitUpdate(LoginRequiredMixin, UpdateView):
  model = Trait
  fields = ['name']

class TraitDelete(LoginRequiredMixin, DeleteView):
  model = Trait
  success_url = '/traits/'

@login_required
def add_photo(request, relationship_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            photo = Photo(url=url, relationship_id=relationship_id)
            photo.save()
        except:
            print('An error occurred')
    return redirect('detail', relationship_id=relationship_id)

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign-up - try again!'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About The Audacity</h1>
<hr />
<p>Have you dated someone with too much audacity? Same, girl.</p>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>The Audacity</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;The Audacity</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'traits_create' %}">Add a Trait</a></li>
            <li><a href="{% url 'traits_index' %}">View All Traits</a></li>
          <li><a href="{% url 'relationship_create' %}">Add a Relationship</a></li>
          <li><a href="/relationships">My Relationships</a></li>
          <li><a href="{% url 'logout' %}">Log Out</a></li>
  {% else %}
  <li><a href="{% url 'signup' %}">Sign Up</a></li>
  <li><a href="{% url 'login' %}">Log In</a></li>
{% endif %}
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2022 The Audacity &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/main_app/sigother_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Relationship</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' sigother.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/sigother_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add a Relationship</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/trait_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Trait</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'traits_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/trait_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Trait Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ trait.name }}</span>
      </div>
      <div class="card-action">
        <a href="{% url 'traits_update' trait.id %}">Edit</a>
        <a href="{% url 'traits_delete' trait.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/trait_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Trait</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/trait_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Trait List</h1>

{% for trait in trait_list %}
  <a href="{% url 'traits_detail' trait.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ trait.name }}</span>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/relationships/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Relationship Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ relationship.name }}</span>
        <p>How we met: {{ relationship.met }}</p>
        <p>Description: {{ relationship.description }}</p>
        <p>Why we broke up: {{ relationship.break_up }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'relationship_update' relationship.id %}">Edit</a>
        <a href="{% url 'relationship_delete' relationship.id %}">Delete</a>
      </div>
    </div>
    {% for photo in relationship.photo_set.all %}
     <img class="responsive-img card-panel" src="{{photo.url}}" alt= "photo of significant other">
  {% empty %}
    <div class="card-panel teal-text center-align">No Photos Uploaded</div>
  {% endfor %}
  <form action="{% url 'add_photo' relationship.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
    {% csrf_token %}
    <input type="file" name="photo-file">
    <br><br>
    <input type="submit" class="btn" value="Upload Photo">
</form>
  </div>
  <div class="col s6">
    <form action="{% url 'add_meeting' relationship.id %}" method="post">
        {% csrf_token %}
        {{ meetings_form.as_p }}
        <input type="submit" class="btn" value="Add Meeting">
      </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Location</th><th>Rating</th><th>Details</th></tr>
      </thead>
      <tbody>
        {% for dates in relationship.meetings_set.all %}
          <tr>
            <td>{{dates.date}}</td>
            <td>{{dates.location}}</td>
            <td>{{dates.rating}}/10</td>
            <td>{{dates.details}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <hr>
  <div class="row">
    <div class="col s6">
      <h3>{{ relationship.name }}'s Traits</h3>
      {% if relationship.traits.count %}
        {% for trait in relationship.traits.all %}
          <div class="card">
        <div class="card-content">
          <span class="card-title">
            {{ trait.name }}
              </span>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <h5>No Traits :(</h5>
      {% endif %}
    </div>
    <div class="col s6">
      <h3>Available Traits</h3>
      {% if traits.count %}
        {% for trait in traits.all %}
          <div class="card">
            <div class="card-content">
              <span class="card-title">
                 {{ trait.name }}
              </span>
            </div>
            <div class="card-action">
              <form action="{% url 'assoc_trait' relationship.id trait.id %}" method="post">
                  {% csrf_token %}
                <button type="submit" class="btn">Add</button>
              </form>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <h5>{{relationship.name}} Already Has All Traits Available</h5>
      {% endif %}
    </div>
</div>
<script>
    var dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });
</script>
{% endblock %}

main_app/templates/relationships/index.html
{% extends 'base.html' %}
{% block content %}

<h1>My Past Relationships</h1>

{% for relationship in relationships %}
  <div class="card">
    <a href="{% url 'detail' relationship.id %}">
    <div class="card-content">
      <span class="card-title">{{ relationship.name }}</span>
      <p>How we met: {{ relationship.met }}</p>
      <p>Description: {{ relationship.description }}</p>
      <p>Why we broke up: {{ relationship.break_up }}</p>
    </div>
  </div>
{% endfor %}

{% endblock %}